import { ConfLectureType } from "../../defDatas";

export const GoogleIO2024_Lectures: ConfLectureType[] = [
  {
    id: "ch_2024_google_1",
    title: "Google Keynote(Google I/O 2024)",
    description:
      "Google이 전 세계의 정보를 체계화하여 누구든 손쉽게 액세스하고 활용하도록 하기 위한 사명을 어떻게 실천하는지 확인하세요.",
    thumbnailURL: "https://img.youtube.com/vi/XEzRZ35urlk/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/XEzRZ35urlk",
    createdAt: "2024-05-14T19:03:02Z",
    href: "/conferencelog/google-io/ch_2024_google_1",
    conferenceId: "ch_2024_google",
    visible: true,
  },
  {
    id: "ch_2024_google_2",
    title: "개발자 기조연설",
    description:
      "Google의 최신 개발자 도구에 대해 알아보고 이 도구로 어떻게 혁신을 촉진하고 생산성을 향상하는지 알아보세요.",
    thumbnailURL: "https://img.youtube.com/vi/ddcZnW1HKUY/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/ddcZnW1HKUY",
    createdAt: "2024-05-14T22:01:55Z",
    href: "/conferencelog/google-io/ch_2024_google_2",
    conferenceId: "ch_2024_google",
    visible: true,
  },
  {
    id: "ch_2024_google_3",
    title: "Android에 관한 새로운 소식",
    description:
      "생성형 AI, Android 15, 폼 팩터, Jetpack, Compose, 도구, 성능 등을 주제로 하는 Android 개발에 관한 최신 정보를 확인하세요.",
    thumbnailURL: "https://img.youtube.com/vi/_yWxUp86TGg/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/_yWxUp86TGg",
    createdAt: "2024-05-16T14:01:15Z",
    href: "/conferencelog/google-io/ch_2024_google_3",
    conferenceId: "ch_2024_google",
    visible: true,
  },
  {
    id: "ch_2024_google_4",
    title: "Google AI에 관한 새로운 소식",
    description:
      "Google의 최신 AI 도구를 경험하고 Gemini API, Google AI Studio, Gemma, Kaggle Models 및 Google 오픈소스 라이브러리(Keras, JAX 포함)의 새로운 기능을 확인하세요.",
    thumbnailURL: "https://img.youtube.com/vi/fH4xqeu7GT0/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/fH4xqeu7GT0",
    createdAt: "2024-05-16",
    keyTags: ["AI", "Google AI"],
    href: "/conferencelog/google-io/ch_2024_google_4",
    conferenceId: "ch_2024_google",
    visible: false,
  },
  {
    id: "ch_2024_google_5",
    title: "Android 개발 도구의 새로운 기능",
    description:
      "Android 앱 개발자를 위한 Android 스튜디오의 새로운 기능을 알아보세요. 몇 가지 데모를 공유하고 Android API, Firebase, Google AI 전반에서 개발자의 워크플로를 가속화할 수 있는 관련 기능을 보여드립니다.",
    thumbnailURL: "https://img.youtube.com/vi/2wOfYgIMf-A/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/2wOfYgIMf-A",
    createdAt: "2024-05-16T14:02:43Z",
    keyTags: ["Android", "Android Studio", "Firebase"],
    href: "/conferencelog/google-io/ch_2024_google_5",
    conferenceId: "ch_2024_google",
    visible: true,
  },
  {
    id: "ch_2024_google_6",
    title: "Flutter에 관한 새로운 소식",
    description:
      "Flutter의 최신 업데이트 소식을 알아보세요. Gemini API를 사용해 보고, 교차 플랫폼 게임 빌드하며, Impeller를 통해 Flutter Android 애플리케이션의 성능을 개선하고 실험적인 Dart 매크로 기능을 미리 볼 수 있습니다. 또한 Wasm으로 Flutter 웹 애플리케이션 성능을 개선하는 방법도 확인해 보세요.",
    thumbnailURL: "https://img.youtube.com/vi/lpnKWK-KEYs/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/lpnKWK-KEYs",
    createdAt: "2024-05-16T14:05:22Z",
    keyTags: ["Flutter", "Dart", "Gemini", "Impeller", "Macros", "WebAssembly"],
    href: "/conferencelog/google-io/ch_2024_google_6",
    conferenceId: "ch_2024_google",
    visible: true,
  },
  {
    id: "ch_2024_google_7",
    title: "Gen AI 기능 구축을 위한 Firebase의 새로운 기능",
    description:
      "프로덕션에 즉시 사용 가능한 Gen AI 앱을 빌드, 배포, 최적화할 수 있는 Firebase의 새로운 서비스와 업데이트된 서비스에 대해 알아보세요. 이러한 앱은 최신 클라우드 데이터베이스와 통합되어 인프라를 관리하는 수고를 덜어줍니다.",
    thumbnailURL: "https://img.youtube.com/vi/2MvV-YX1eKw/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/2MvV-YX1eKw",
    createdAt: "2024-05-16T14:04:13Z",
    keyTags: [
      "Firebase",
      "Gen AI",
      "Gemini",
      "Firebase Data Connect",
      "GenKit",
      "Vertex AI",
    ],
    href: "/conferencelog/google-io/ch_2024_google_7",
    conferenceId: "ch_2024_google",
    visible: true,
  },
  {
    id: "ch_2024_google_8",
    title: "Google Play에 관한 새로운 소식",
    description:
      "Google Play에서 비즈니스 성장에 도움이 되는 최신 도구와 업데이트에 대해 알아보세요.",
    thumbnailURL: "https://img.youtube.com/vi/xry2mQbWrio/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/xry2mQbWrio",
    createdAt: "2024-05-16",
    keyTags: ["Google Play"],
    href: "/conferencelog/google-io/ch_2024_google_8",
    conferenceId: "ch_2024_google",
    visible: false,
  },
  {
    id: "ch_2024_google_9",
    title: "웹에 관한 새로운 소식",
    description:
      "Baseline은 개발자에게 웹 기능과 API의 상호 운용성 상태를 이해할 수 있는 방법을 제시합니다. MDN, Can I Use, web.dev와 같은 주요 개발자 리소스 사이트에서 명확한 상태 정보를 확인할 수 있으므로 이제 기능을 사용할 준비가 되었는지 여부를 그 어느 때보다 쉽게 알 수 있습니다. 이 강연에서는 현재 Baseline에 포함되어 더욱 아름답고 기능이 풍부한 사이트와 애플리케이션을 만드는 데 도움이 되는 주요 기능 중 일부를 다룹니다.",
    thumbnailURL: "https://img.youtube.com/vi/W8bokbLn1G8/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/W8bokbLn1G8",
    createdAt: "2024-05-16",
    href: "/conferencelog/google-io/ch_2024_google_9",
    conferenceId: "ch_2024_google",
    visible: false,
  },
  {
    id: "ch_2024_google_10",
    title: "AI 기반 솔루션: 사회를 위한 건강과 과학의 재구상",
    description:
      "AI는 건강, 의료, 기후, 교육을 비롯해 전 세계적으로 가장 커다란 문제들을 해결할 수 있는 잠재력이 있습니다. AI가 어떻게 연구자와 과학자가 새로운 길을 모색하는 데 도움을 주는지 알아보세요.",
    thumbnailURL: "https://img.youtube.com/vi/N_l9038Fy8A/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/N_l9038Fy8A",
    createdAt: "2024-05-16",
    href: "/conferencelog/google-io/ch_2024_google_10",
    conferenceId: "ch_2024_google",
    visible: false,
  },
  {
    id: "ch_2024_google_11",
    title: "Google AI 속속들이 살펴보기",
    description:
      "기술과 사회에 관한 담화 Google AI 팀과 함께 심층 분석을 수행해 보세요. Google AI의 기반이 되는 기술과 연구, 새로운 혁신, 앞으로의 흥미진진한 기회에 대해 자세히 알아보세요.",
    thumbnailURL: "https://img.youtube.com/vi/8Pl5dPja0UE/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/8Pl5dPja0UE",
    createdAt: "2024-05-16",
    href: "/conferencelog/google-io/ch_2024_google_11",
    conferenceId: "ch_2024_google",
    visible: false,
  },
  {
    id: "ch_2024_google_12",
    title: "양자 컴퓨팅: 사실과 허구, 그리고 미래",
    description:
      "기술과 사회에 관한 담화 요즘 양자 컴퓨팅에 대한 관심이 매우 높아 무엇이 진실이고 무엇이 과장인지 구분하지 못할 정도입니다. 양자 컴퓨터가 해낼 수 있는 일은 무엇이고, 해내지 못하는 일은 무엇일까요? Google Quantum AI 팀과 함께 첨단 기술의 세계로 떠나 현재 상태를 알아보고 사실과 허구를 분간하며, 앞으로의 미래에 대비해 보세요.",
    thumbnailURL: "https://img.youtube.com/vi/rTx5nw3AgnY/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/rTx5nw3AgnY",
    createdAt: "2024-05-16",
    href: "/conferencelog/google-io/ch_2024_google_12",
    conferenceId: "ch_2024_google",
    visible: false,
  },
  {
    id: "ch_2024_google_13",
    title: "Google Cloud와 Google Workspace에 관한 새로운 소식",
    description:
      "개발자가 Google Cloud와 Workspace에 대해 배우고, 구축하고, 더 많은 작업을 수행할 수 있도록 지원하는 최신 도구와 업데이트에 대해 알아보세요.",
    thumbnailURL: "https://img.youtube.com/vi/0QbUYfTRJEY/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/0QbUYfTRJEY",
    createdAt: "2024-05-16",
    href: "/conferencelog/google-io/ch_2024_google_13",
    conferenceId: "ch_2024_google",
    visible: false,
  },
  {
    id: "ch_2024_google_14",
    title: "Android 접근성 기능 및 API 업데이트",
    description:
      "Android의 최신 접근성 기능과 앱 개발자를 위한 권장사항에 대해 알아보세요. 이 세션에서는 Android 생태계 전반에서 장애인의 요구사항을 충족하는 방법을 공유합니다. 또한 개발자가 최신 접근성 도구와 API를 사용하여 접근성이 뛰어난 인앱 환경을 제공하는 방법에 대한 가이드도 제시합니다.",
    thumbnailURL: "https://img.youtube.com/vi/qLCK0HO_tNQ/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/qLCK0HO_tNQ",
    createdAt: "2024-05-16",
    href: "/conferencelog/google-io/ch_2024_google_14",
    conferenceId: "ch_2024_google",
    visible: false,
  },
  {
    id: "ch_2024_google_15",
    title: "Android 스튜디오에서 실행 가능한 앱 프로파일링",
    description:
      "Android 스튜디오 프로파일러는 Android 앱의 성능 문제를 이해하고 해결하는 데 도움이 되는 강력한 도구입니다. 이 세션에서는 이전보다 앱을 더 실행 가능하고 유용하게 만드는 Android 스튜디오 프로파일러의 새로운 기능을 알아보세요. 또한 완전히 새로워진 프로파일러도 소개합니다.",
    thumbnailURL: "https://img.youtube.com/vi/ELKKWDPCLXU/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/ELKKWDPCLXU",
    createdAt: "2024-05-16",
    href: "/conferencelog/google-io/ch_2024_google_15",
    conferenceId: "ch_2024_google",
    visible: false,
  },
  {
    id: "ch_2024_google_16",
    title: "Android 온디바이스 Gen AI의 작동 원리",
    description:
      "Android 온디바이스 Gen AI에 대해 알아보세요. 이 세션에서는 Android에서 사용할 수 있는 다양한 온디바이스 Gen AI 솔루션과 온디바이스 추론의 장점을 살펴봅니다. 또한 온디바이스 Gen AI를 채택한 일부 앱을 소개하고 AICore에 대한 기술적 심층 분석을 통해 AICore의 설계 방식과 미세 조정을 위한 LoRA 기법을 살펴봅니다.",
    thumbnailURL: "https://img.youtube.com/vi/nOinQrCvZkM/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/nOinQrCvZkM",
    createdAt: "2024-05-16T14:02:36Z",
    href: "/conferencelog/google-io/ch_2024_google_16",
    conferenceId: "ch_2024_google",
    visible: true,
  },
  {
    id: "ch_2024_google_17",
    title: "Android에서 백그라운드 작업의 배터리 효율 향상",
    description:
      "이 기술 세션에서는 백그라운드 작업과 배터리 소모가 어떻게 연결되는지에 대한 통찰력을 공유하고 최신 버전의 Android에서 백그라운드 작업의 배터리 효율을 향상하는 방법에 대한 가이드를 제시합니다. 모바일 기기와 Wear 기기 모두에서 WorkManager와 포그라운드 서비스(FGS)를 사용하여 배터리 효율을 향상하기 위한 권장사항을 살펴봅니다. 또한 Perfetto를 사용하여 네트워크 사용량과 전력을 디버깅하여 배터리 효율을 더욱 향상하는 방법도 알아봅니다.",
    thumbnailURL: "https://img.youtube.com/vi/jS46zP8kQ3k/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/jS46zP8kQ3k",
    createdAt: "2024-05-16",
    href: "/conferencelog/google-io/ch_2024_google_17",
    conferenceId: "ch_2024_google",
    visible: false,
  },
  {
    id: "ch_2024_google_18",
    title: "Android에서 사용자 보안 보호",
    description:
      "이 세션에서는 필수 Android 보안 업데이트, 사기와 기기 도난에 대비해 사용자 보호 기능을 개선하는 방법, 최신 Play Integrity API 기능을 사용하여 새로운 위협으로부터 앱을 보호하는 방법을 다룹니다.",
    thumbnailURL: "https://img.youtube.com/vi/RccJYep2v5I/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/RccJYep2v5I",
    createdAt: "2024-05-16",
    href: "/conferencelog/google-io/ch_2024_google_18",
    conferenceId: "ch_2024_google",
    visible: false,
  },
  {
    id: "ch_2024_google_19",
    title: "CameraX로 Flutter에서 완벽한 카메라 환경 구축",
    description:
      "기기별로 뉘앙스를 고려할 때 다양한 Android 기종에 걸쳐 안정적인 카메라 경험을 유지하기 어려울 수 있습니다. Android의 CameraX는 카메라 개발을 간편하게 해주고 기종과 관계없이 카메라 동작을 일관되게 유지하도록 구축한 카메라 라이브러리로, 그러한 고충점을 대부분 해결해 줍니다. 따라서 Flutter 생태계에서도 당연히 지원됩니다. CameraX로 구축한 새 Flutter 카메라 플러그인 구현을 사용해 완벽한 카메라 경험을 빌드하는 방법을 알아보세요.",
    thumbnailURL: "https://img.youtube.com/vi/d1sRCa5k2Sg/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/d1sRCa5k2Sg",
    createdAt: "2024-05-16",
    href: "/conferencelog/google-io/ch_2024_google_19",
    conferenceId: "ch_2024_google",
    visible: false,
  },
  {
    id: "ch_2024_google_20",
    title: "Checks를 통해 앱 규정 준수와 AI 안전 간소화",
    description:
      "Checks는 Google의 AI 기반 앱 규정 준수 플랫폼입니다. Checks로 개인 정보 보호 규정 준수를 간소화하고 더 빠르게 확신을 갖고 앱을 실행하는 방법을 알아보세요. Checks는 설정이 쉽고 워크플로에 직접 통합되며 이제 책임감 있고 안전하게 생성형 AI를 앱에 구축하는 데 도움이 되는 솔루션을 제공합니다.",
    thumbnailURL: "https://img.youtube.com/vi/8sG2TGgyvtk/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/8sG2TGgyvtk",
    createdAt: "2024-05-16",
    href: "/conferencelog/google-io/ch_2024_google_20",
    conferenceId: "ch_2024_google",
    visible: false,
  },
  {
    id: "ch_2024_google_21",
    title: "Flutter로 적응형 UI를 개발하는 방법",
    description:
      "휴대전화, 태블릿, 폴더블 기기, 데스크톱에서 멋지게 잘 작동하는 적응형 UI로 Flutter 앱을 개선하세요. 마우스, 키보드 등 다양한 입력 모드를 처리하여 모든 기기에서 원활한 환경을 만드는 방법을 알아보세요. 적응력이 뛰어나고 사용자 친화적인 Flutter 앱을 개발하는 데 도움이 되는 강력한 적응형 위젯, 새로운 디스플레이 API, 간단한 규칙을 살펴보세요.",
    thumbnailURL: "https://img.youtube.com/vi/LeKLGzpsz9I/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/LeKLGzpsz9I",
    createdAt: "2024-05-16",
    href: "/conferencelog/google-io/ch_2024_google_21",
    conferenceId: "ch_2024_google",
    visible: false,
  },
  {
    id: "ch_2024_google_22",
    title: "Jetpack Glance를 사용한 Android 위젯 구축",
    description:
      "Compose 기술과 Jetpack Compose를 사용하여 사용자의 홈 화면에서 실행할 수 있는(곧 더 많은 곳에서 사용할 수 있는) 애플리케이션의 작은 부분인 우수한 품질의 위젯을 만드는 방법을 알아보세요. Glance 1.1.0 업데이트, 우수한 품질의 위젯 가이드라인, 사용 사례, Jetpack Glance를 사용하여 Android에서 Compose 방식으로 위젯을 만드는 데 필요한 모든 것을 다룹니다.",
    thumbnailURL: "https://img.youtube.com/vi/jI1LKN7jBVk/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/jI1LKN7jBVk",
    createdAt: "2024-05-16T14:02:00Z",
    href: "/conferencelog/google-io/ch_2024_google_22",
    conferenceId: "ch_2024_google",
    visible: true,
  },
  {
    id: "ch_2024_google_23",
    title: "Material 3 적응형 라이브러리를 사용한 UI 개발",
    description:
      "현재 베타 버전인 Material 3 적응형 라이브러리를 사용하여 적응형 UI를 개발합니다. 목록 세부정보와 지원 창 표준 레이아웃을 위한 새로운 Composable을 사용하여 표시되는 창 수를 자동으로 조정하고, 창 크기 클래스를 기반으로 탐색 UI 구성요소 간에 쉽게 전환하고, 빌딩 블록 Composable을 사용하여 자체 맞춤 환경을 구축할 수 있습니다.",
    thumbnailURL: "https://img.youtube.com/vi/xPUZENis4gc/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/xPUZENis4gc",
    createdAt: "2024-05-16",
    href: "/conferencelog/google-io/ch_2024_google_23",
    conferenceId: "ch_2024_google",
    visible: false,
  },
  {
    id: "ch_2024_google_24",
    title: "생성형 AI로 구동되는 Android 앱 직접 만들기",
    description:
      "Android 앱에 Gemini API와 생성형 AI 기반 기능을 포함하는 방법을 알아보세요.",
    thumbnailURL: "https://img.youtube.com/vi/L2ORMj0yak8/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/L2ORMj0yak8",
    createdAt: "2024-05-16T14:02:30Z",
    href: "/conferencelog/google-io/ch_2024_google_24",
    conferenceId: "ch_2024_google",
    visible: true,
  },
  {
    id: "ch_2024_google_25",
    title: "패스키와 디지털 ID 모범 사례",
    description:
      "패스키는 원활하고 안전하며 신뢰할 수 있는 로그인 사용자 흐름을 구현하기 위한 최신 표준입니다. Credential Manager를 통한 패스키와 Google로 로그인을 사용하여 인증 및 계정 생성 환경을 가속화하는 방법을 확인해 보세요. Wear 통합과 자동 완성을 포함하여 새로 출시될 Credential Manager 기능에 대해 알아보세요. 또한 웹과 모바일 전반에서 사용자 환경을 개선하기 위해 지갑 기반 솔루션과 함께 Google로 로그인을 사용하는 교차 플랫폼 ID 전략을 살펴보세요.",
    thumbnailURL: "https://img.youtube.com/vi/fgTOeLShcrY/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/fgTOeLShcrY",
    createdAt: "2024-05-16T14:07:13Z",
    href: "/conferencelog/google-io/ch_2024_google_25",
    conferenceId: "ch_2024_google",
    visible: true,
  },
  {
    id: "ch_2024_google_26",
    title: "확장 가능한 Compose API 설계",
    description:
      "이 강연에서는 관용적 Compose API 개발을 위한 권장사항과 가이드라인을 다룹니다. 구성요소를 생각하고 계획하는 방법, Kotlin 및 명명 규칙을 활용하는 방법, 구성요소에 필요한 견고한 구조를 정의하는 방법, 이러한 API를 확인하고 유지 관리하는 방법을 살펴봅니다. 이러한 가이드라인이 개발자가 보다 확장 가능하고 성능이 뛰어나며 일관성이 있는 코드를 작성하는 데 어떻게 도움이 되는지 설명합니다.",
    thumbnailURL: "https://img.youtube.com/vi/JvbyGcqdWBA/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/JvbyGcqdWBA",
    createdAt: "2024-05-16",
    href: "/conferencelog/google-io/ch_2024_google_26",
    conferenceId: "ch_2024_google",
    visible: true,
  },
  {
    id: "ch_2024_google_27",
    title: "Material for Compose로 더 빨라지고 표현력이 풍부해진 디자인",
    description:
      "개발자가 접근성 높은 맞춤형 제품과 보다 포괄적인 Compose 제품을 만들 수 있도록 지원하는 색상과 서체 업데이트를 포함하여 Material Design의 최신 소식을 확인하세요. 그런 다음 Google 지도를 미리 살펴보고 이 모든 것이 어떻게 결합되는지, 그리고 Material for Compose를 사용하여 프로덕션에 기능을 제공하는 방법을 알아보세요.",
    thumbnailURL: "https://img.youtube.com/vi/XQ_Hvu-s7JY/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/XQ_Hvu-s7JY",
    createdAt: "2024-05-16",
    href: "/conferencelog/google-io/ch_2024_google_27",
    conferenceId: "ch_2024_google",
    visible: false,
  },
  {
    id: "ch_2024_google_28",
    title: "JavaScript 프레임워크 생태계 탐색",
    description:
      "JavaScript 프레임워크 생태계의 현재 상태와 미래에 대해 알아보세요. JavaScript 프레임워크 생태계의 현재 트렌드, 미래 전망, Google의 참여, 그리고 JavaScript 프레임워크 생태계의 미래에 대해 알아보세요.",
    thumbnailURL: "https://img.youtube.com/vi/XaNqdlfVF-M/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/XaNqdlfVF-M",
    createdAt: "2024-05-16T14:08:15Z",
    href: "/conferencelog/google-io/ch_2024_google_28",
    conferenceId: "ch_2024_google",
    visible: true,
  },
  {
    id: "ch_2024_google_29",
    title:
      "Jetpack Compose(Kotlin)를 사용한 Android 앱의 지도에 대한 자세한 내용",
    description:
      "Maps Compose 라이브러리는 단순한 지도와 마커를 넘어 성장했습니다. 이 워크숍에서는 마커 클러스터링을 통해 대규모 데이터 세트의 효율적인 관리를 살펴보고, 고급 마커의 심미적 매력을 활용하고, 계층화된 앱 아키텍처 내에서 Compose의 잠재력을 활용합니다. 결국에는 앱을 새로운 차원으로 끌어올릴 수 있는 매력적인 고성능 지도 기능을 만드는 기술을 습득하게 됩니다.",
    thumbnailURL: "https://img.youtube.com/vi/4eARovV-Bq4/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/4eARovV-Bq4",
    createdAt: "2024-05-16",
    href: "/conferencelog/google-io/ch_2024_google_29",
    conferenceId: "ch_2024_google",
    visible: false,
  },
  {
    id: "ch_2024_google_30",
    title: "모든 JavaScript 프레임워크를 Cloud Run에 배포하는 방법",
    description:
      "JavaScript 생태계는 너무 빠르게 변하기 때문에 [JavaScript 프레임워크]를 Google Cloud Run에 배포할 수 있을지 의문이 생깁니다. 배포할 수 있습니다. 가능한 한 빨리 JavaScript 프레임워크를 배포하여 이를 증명해 보겠습니다. 참여하려면 소유자가 본인인 Google Cloud 프로젝트를 하나 만들어야 합니다. 또는 Cloud Run Node.js Quickstart를 완료해 모든 기능이 제대로 작동하는지 확인하세요",
    thumbnailURL: "https://img.youtube.com/vi/eemS-UTjdb0/0.jpg",
    youtubeLink: "https://www.youtube.com/embed/eemS-UTjdb0",
    createdAt: "2024-05-16",
    href: "/conferencelog/google-io/ch_2024_google_30",
    conferenceId: "ch_2024_google",
    visible: false,
  },
];
